# Generated by Django 3.2.8 on 2022-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_airLiner',
            field=models.BooleanField(default=False),
        ),
    ]
