# Generated by Django 3.2.8 on 2022-08-10 09:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='OrderBookS',
        ),
    ]
