# Generated by Django 3.2.8 on 2022-08-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_book_orderbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookName', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderbooks',
            name='author',
        ),
        migrations.RemoveField(
            model_name='orderbooks',
            name='bookName',
        ),
        migrations.AddField(
            model_name='orderbooks',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.book'),
        ),
    ]
